### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by xsikq** [luckyzyx/ToolboxUnlock#1]
after the premium feature is clicked, the dialog appears then disappears and nothing happens

**Comment by luckyzyx** [comment]
> after the premium feature is clicked, the dialog appears then disappears and nothing happens

You can try to make multiple clicks, and it works normally on my side.

**Comment by xsikq** [comment]
> > after the premium feature is clicked, the dialog appears then disappears and nothing happens
> 
> You can try to make multiple clicks, and it works normally on my side.

still not working :(

**Comment by luckyzyx** [comment]
[#https://github.com/Xposed-Modules-Repo/com.luckyzyx.toolboxunlock/releases/tag/32-1.2](https://github.com/Xposed-Modules-Repo/com.luckyzyx.toolboxunlock/releases/tag/32-1.2)
The latest version has been tested.
